spring.application.name=payment-service

# Server
server.port=8083

# Kafka
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=payment-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Topic
spring.kafka.topic.name=payment-events
#raw topic
spring.kafka.consume.topic.name=inventory-events